[package]
name = "neli"
edition = "2018"
version = "0.4.3"
authors = ["John Baublitz <john.m.baublitz@gmail.com>"]
description = "Type safe netlink library written in Rust"
license = "BSD-3-Clause"
repository = "https://github.com/jbaublitz/neli"
keywords = ["netlink"]
include = [
    "**/*.rs",
    "Cargo.toml",
    "LICENSE",
]

[lib]
name = "neli"
path = "src/lib.rs"

[dependencies]
byteorder = "1.2"
libc = "0.2.66"
smallvec = "0.6"
bytes = "0.4"

[dependencies.log]
version = "0.4"
optional = true

[dependencies.simple_logger]
version = "1.6.0"
optional = true

[dependencies.lazy_static]
version = "1.4"
optional = true

[dependencies.tokio]
version = "0.2"
features = ["io-driver", "stream"]
optional = true

[dependencies.mio]
version = "0.6.20"
optional = true

[features]
default = []
async = ["tokio", "mio"]
netfilter = []
logging = ["log", "simple_logger", "lazy_static"]
